# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 73a03d92aa7db1e7662997c13ce84e6122f64aca8088294145ed3a3b9ab188b7e32b8e498aaee84fb48817fd0434c9767ef167f2149e9ec3d1d7cc27b7d6b404

test:
  secret_key_base: 0ac1bc392b9fe3d69c0f1ef4e07d4ce875cf2d359a6afec7d8ac0774f9b0d4125e60f012d0e4110193ce82045336b3448d4fad1706297b56b4809241512d1001

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
